### PR TITLE
Testing view cli

### PR DESCRIPTION
**Pull request by Eyedema**

### CODE REVIEW

**Comment by Eyedema** [comment]
Last couple of commits were due surviving mutators in the CLI classes. The issue was resolved by testing the method that prints the whole menu instead of just the string, and by adding a check with a return value (later to be used in the Main) instead of a System.exit() call.

**Comment by Eyedema** [comment]
Low overall coverage is still due to untested exceptions in the TransactionManagerMongoClass @palai103

**Comment by Eyedema** [comment]
Added the IT tests, they should be all done.

**Review by palai103 — APPROVED** [review]
Everything ok, we just have to remember to add the CFU field in the Course constructor

**Pull request merged**
